---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: ./test/data_bags

platforms:
#  - name: centos-6.5
#    driver:
#      vm_hostname: localhost
  - name: ubuntu-14.04
    driver:
      vm_hostname: localhost


suites:
  - name: default
    encrypted_data_bag_secret_key_path: ./test_encyrpted_data_bag_secret
    run_list:
      - recipe[luks_test]
    attributes: {}
